### ISSUE TITLE
If this plugin is used together with other default plugin task names could clash

### ISSUE THREAD

**Issue by billsegall** [echocat/gradle-golang-plugin#20]
When trying to add the gradle-golang plugin to https://github.com/real-logic/simple-binary-encoding I see:

* What went wrong:
An exception occurred applying plugin request [id: 'java']
> Failed to apply plugin [class 'org.gradle.language.base.plugins.LifecycleBasePlugin']
   > Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.

This seem similar to https://github.com/GradleFx/GradleFx/issues/235 which was fixed by this patch: https://github.com/GradleFx/GradleFx/commit/0a8bf8997cc2c31f7edb66c6260dc6f4987f1d91

**Comment by blaubaer** [comment]
Hi @billsegall!

I understand your problem. Your problem is, that you mix up and java project with an golang project at once. This is not directly a bug of this plugin. Same things will happen if you mix up other source code types within gradle.

I purpose to add a `/gocode/build.gradle` with depends only on `golang-gradle-plugin` and add subcall for `generateGolangCodecs` to your `/build.gradle` in the root of your project.

But I will check if it is possible to rename this build steps in special cases.

Cheers,
Gregor

**Comment by blaubaer** [comment]
I found a way. I've created a plugin extension. It is named `org.echocat.golang-minor` instead `org.echocat.golang`. If the minor version is used every tasks is prefixed with `golang` and the next letter is capitalized .. example: `build` -> `golangBuild`.

I hope I can release this as expected. 😄

**Comment by blaubaer** [comment]
Ok I have released this and also tested. All went as expected. Please use in your case the plugin with id `org.echocat.golang-minor` instead of `org.echocat.golang` in version `0.1.15` and each task is prefixed with `golang`.
